/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTagBox: typeof import('./src/components/box/AddTagBox.vue')['default']
    ArticleCard: typeof import('./src/components/card/ArticleCard.vue')['default']
    ButtonClear: typeof import('./src/components/nav/ButtonClear.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    LogoTitle: typeof import('./src/components/nav/LogoTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/nav/SearchBox.vue')['default']
    SearchNavbar: typeof import('./src/components/common/SearchNavbar.vue')['default']
    SliderCaptcha: typeof import('./src/components/canvas/SliderCaptcha.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/nav/ThemeToggle.vue')['default']
    ToolCard: typeof import('./src/components/card/ToolCard.vue')['default']
    TopicCard: typeof import('./src/components/card/TopicCard.vue')['default']
    WordCaptcha: typeof import('./src/components/canvas/WordCaptcha.vue')['default']
  }
}
