/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTagBox: typeof import('./src/components/box/AddTagBox.vue')['default']
    ArticleCard: typeof import('./src/components/card/ArticleCard.vue')['default']
    ButtonClear: typeof import('./src/components/nav/ButtonClear.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LogoTitle: typeof import('./src/components/nav/LogoTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/nav/SearchBox.vue')['default']
    SearchNavbar: typeof import('./src/components/common/SearchNavbar.vue')['default']
    SliderCaptcha: typeof import('./src/components/canvas/SliderCaptcha.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/nav/ThemeToggle.vue')['default']
    ToolCard: typeof import('./src/components/card/ToolCard.vue')['default']
    TopicCard: typeof import('./src/components/card/TopicCard.vue')['default']
    WordCaptcha: typeof import('./src/components/canvas/WordCaptcha.vue')['default']
  }
}
